export const imageList = [
  '/images/bung/img_thumbnail_1.png',
  '/images/bung/img_thumbnail_2.png',
  '/images/bung/img_thumbnail_3.png',
  '/images/bung/img_thumbnail_4.png',
  '/images/bung/img_thumbnail_5.png',
  '/images/bung/img_thumbnail_6.png',
  '/images/bung/img_thumbnail_7.png',
  '/images/bung/img_thumbnail_8.png',
  '/images/bung/img_thumbnail_9.png',
  '/images/bung/img_thumbnail_10.png',
  '/images/bung/img_thumbnail_11.png',
  '/images/bung/img_thumbnail_12.png',
  '/images/bung/img_thumbnail_13.png',
]
