export enum MESSAGE {
  REQUEST_GEOLOCATION = 'REQUEST_GEOLOCATION',
  GEOLOCATION = 'GEOLOCATION',
  GEOLOCATION_ERROR = 'GEOLOCATION_ERROR',

  REQUEST_SMART_WALLET_CONNECT = 'REQUEST_SMART_WALLET_CONNECT',
  RESPONSE_SMART_WALLET_CONNECT = 'RESPONSE_SMART_WALLET_CONNECT',
  RESPONSE_SMART_WALLET_CONNECT_ERROR = 'RESPONSE_SMART_WALLET_CONNECT_ERROR',
  DISCONNECT_SMART_WALLET = 'DISCONNECT_SMART_WALLET',
  WALLET_MODAL_CLOSED = 'WALLET_MODAL_CLOSED',
}
