export enum MESSAGE {
  REQUEST_GEOLOCATION = 'REQUEST_GEOLOCATION',
  GEOLOCATION = 'GEOLOCATION',
  GEOLOCATION_ERROR = 'GEOLOCATION_ERROR',

  REQUEST_SMART_WALLET_CONNECT = 'REQUEST_SMART_WALLET_CONNECT',
  RESPONSE_SMART_WALLET_CONNECT = 'RESPONSE_SMART_WALLET_CONNECT',
  RESPONSE_SMART_WALLET_CONNECT_ERROR = 'RESPONSE_SMART_WALLET_CONNECT_ERROR',
  DISCONNECT_SMART_WALLET = 'DISCONNECT_SMART_WALLET',
  WALLET_MODAL_CLOSED = 'WALLET_MODAL_CLOSED',

  REQUEST_VIBRATION = 'REQUEST_VIBRATION',

  INSET = 'INSET',
}

// 진동 타입 정의
export enum VIBRATION_TYPE {
  // Impact 피드백 (충격감)
  IMPACT_LIGHT = 'IMPACT_LIGHT',
  IMPACT_MEDIUM = 'IMPACT_MEDIUM',
  IMPACT_HEAVY = 'IMPACT_HEAVY',
  IMPACT_RIGID = 'IMPACT_RIGID',
  IMPACT_SOFT = 'IMPACT_SOFT',
  
  // Notification 피드백 (알림)
  NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS',
  NOTIFICATION_WARNING = 'NOTIFICATION_WARNING',
  NOTIFICATION_ERROR = 'NOTIFICATION_ERROR',
  
  // Selection 피드백 (선택)
  SELECTION = 'SELECTION',
}
