import { ResponseType } from './type'

export function fetchNftList(): Promise<ResponseType> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        message: 'success',
        data: mockData,
      })
    }, 100)
  })
}

/**
 * TODO 썸네일 이미지 URL 추가
 * TODO 머리의 경우 앞, 뒤 따로 URL 추가
 */
const mockData: ResponseType['data'] = [
  {
    id: '00001',
    imageUrl: '/temp/avatar/nft_body_accessories_1.png',
    rarity: 'common',
    name: 'body_accessories_1',
    mainCategory: 'accessories',
    subCategory: 'body-accessories',
    link: '',
  },
  {
    id: '00002',
    imageUrl: '/temp/avatar/nft_body_accessories_2.png',
    rarity: 'common',
    name: 'body_accessories_2',
    mainCategory: 'accessories',
    subCategory: 'body-accessories',
    link: '',
  },
  {
    id: '00003',
    imageUrl: '/temp/avatar/nft_body_accessories_3.png',
    rarity: 'common',
    name: 'body_accessories_3',
    mainCategory: 'accessories',
    subCategory: 'body-accessories',
    link: '',
  },
  {
    id: '00004',
    imageUrl: '/temp/avatar/nft_ear_accessories_1.png',
    rarity: 'common',
    name: 'ear_accessories_1',
    mainCategory: 'accessories',
    subCategory: 'ear-accessories',
    link: '',
  },
  {
    id: '00005',
    imageUrl: '/temp/avatar/nft_ear_accessories_2.png',
    rarity: 'common',
    name: 'ear_accessories_2',
    mainCategory: 'accessories',
    subCategory: 'ear-accessories',
    link: '',
  },
  {
    id: '00006',
    imageUrl: '/temp/avatar/nft_ear_accessories_3.png',
    rarity: 'common',
    name: 'ear_accessories_3',
    mainCategory: 'accessories',
    subCategory: 'ear-accessories',
    link: '',
  },
  {
    id: '00007',
    imageUrl: '/temp/avatar/nft_ear_accessories_4.png',
    rarity: 'common',
    name: 'ear_accessories_4',
    mainCategory: 'accessories',
    subCategory: 'ear-accessories',
    link: '',
  },
  {
    id: '00008',
    imageUrl: '/temp/avatar/nft_face_1.png',
    rarity: 'common',
    name: 'face_1',
    mainCategory: 'face',
    subCategory: null,
    link: '',
  },
  {
    id: '00009',
    imageUrl: '/temp/avatar/nft_face_2.png',
    rarity: 'common',
    name: 'face_2',
    mainCategory: 'face',
    subCategory: null,
    link: '',
  },
  {
    id: '00010',
    imageUrl: '/temp/avatar/nft_face_3.png',
    rarity: 'common',
    name: 'face_3',
    mainCategory: 'face',
    subCategory: null,
    link: '',
  },
  {
    id: '00011',
    imageUrl: '/temp/avatar/nft_face_4.png',
    rarity: 'common',
    name: 'face_4',
    mainCategory: 'face',
    subCategory: null,
    link: '',
  },
  {
    id: '00012',
    imageUrl: '/temp/avatar/nft_face_5.png',
    rarity: 'common',
    name: 'face_5',
    mainCategory: 'face',
    subCategory: null,
    link: '',
  },
  {
    id: '00013',
    imageUrl: '/temp/avatar/nft_hair_1.png',
    rarity: 'common',
    name: 'hair_1',
    mainCategory: 'hair',
    subCategory: null,
    link: '',
  },
  {
    id: '00014',
    imageUrl: '/temp/avatar/nft_hair_2.png',
    rarity: 'common',
    name: 'hair_2',
    mainCategory: 'hair',
    subCategory: null,
    link: '',
  },
  {
    id: '00015',
    imageUrl: '/temp/avatar/nft_hair_3.png',
    rarity: 'common',
    name: 'hair_3',
    mainCategory: 'hair',
    subCategory: null,
    link: '',
  },
  {
    id: '00016',
    imageUrl: '/temp/avatar/nft_hair_4.png',
    rarity: 'common',
    name: 'hair_4',
    mainCategory: 'hair',
    subCategory: null,
    link: '',
  },
  {
    id: '00017',
    imageUrl: '/temp/avatar/nft_hair_accessories_1.png',
    rarity: 'common',
    name: 'hair_accessories_1',
    mainCategory: 'accessories',
    subCategory: 'hair-accessories',
    link: '',
  },
  {
    id: '00018',
    imageUrl: '/temp/avatar/nft_hair_accessories_2.png',
    rarity: 'common',
    name: 'hair_accessories_2',
    mainCategory: 'accessories',
    subCategory: 'hair-accessories',
    link: '',
  },
  {
    id: '00019',
    imageUrl: '/temp/avatar/nft_hair_accessories_3.png',
    rarity: 'common',
    name: 'hair_accessories_3',
    mainCategory: 'accessories',
    subCategory: 'hair-accessories',
    link: '',
  },
  {
    id: '00020',
    imageUrl: '/temp/avatar/nft_lowerClothing_1.png',
    rarity: 'common',
    name: 'lower_clothing_1',
    mainCategory: 'lowerClothing',
    subCategory: null,
    link: '',
  },
  {
    id: '00021',
    imageUrl: '/temp/avatar/nft_lowerClothing_2.png',
    rarity: 'common',
    name: 'lower_clothing_2',
    mainCategory: 'lowerClothing',
    subCategory: null,
    link: '',
  },
  {
    id: '00022',
    imageUrl: '/temp/avatar/nft_lowerClothing_3.png',
    rarity: 'common',
    name: 'lower_clothing_3',
    mainCategory: 'lowerClothing',
    subCategory: null,
    link: '',
  },
  {
    id: '00023',
    imageUrl: '/temp/avatar/nft_lowerClothing_4.png',
    rarity: 'common',
    name: 'lower_clothing_4',
    mainCategory: 'lowerClothing',
    subCategory: null,
    link: '',
  },
  {
    id: '00024',
    imageUrl: '/temp/avatar/nft_skin_1.png',
    rarity: 'common',
    name: 'skin_1',
    mainCategory: 'skin',
    subCategory: null,
    link: '',
  },
  {
    id: '00025',
    imageUrl: '/temp/avatar/nft_skin_2.png',
    rarity: 'common',
    name: 'skin_2',
    mainCategory: 'skin',
    subCategory: null,
    link: '',
  },
  {
    id: '00026',
    imageUrl: '/temp/avatar/nft_skin_3.png',
    rarity: 'common',
    name: 'skin_3',
    mainCategory: 'skin',
    subCategory: null,
    link: '',
  },
  {
    id: '00027',
    imageUrl: '/temp/avatar/nft_skin_4.png',
    rarity: 'common',
    name: 'skin_4',
    mainCategory: 'skin',
    subCategory: null,
    link: '',
  },
  {
    id: '00028',
    imageUrl: '/temp/avatar/nft_upperClothing_1.png',
    rarity: 'common',
    name: 'upper_clothing_1',
    mainCategory: 'upperClothing',
    subCategory: null,
    link: '',
  },
  {
    id: '00029',
    imageUrl: '/temp/avatar/nft_upperClothing_2.png',
    rarity: 'common',
    name: 'upper_clothing_2',
    mainCategory: 'upperClothing',
    subCategory: null,
    link: '',
  },
  {
    id: '00030',
    imageUrl: '/temp/avatar/nft_upperClothing_3.png',
    rarity: 'common',
    name: 'upper_clothing_3',
    mainCategory: 'upperClothing',
    subCategory: null,
    link: '',
  },
  {
    id: '00031',
    imageUrl: '/temp/avatar/nft_upperClothing_4.png',
    rarity: 'common',
    name: 'upper_clothing_4',
    mainCategory: 'upperClothing',
    subCategory: null,
    link: '',
  },
  {
    id: '00032',
    imageUrl: '/temp/avatar/nft_footwear_1.png',
    rarity: 'common',
    name: 'footwear_1',
    mainCategory: 'footwear',
    subCategory: null,
    link: '',
  },
  {
    id: '00033',
    imageUrl: '/temp/avatar/nft_footwear_2.png',
    rarity: 'common',
    name: 'footwear_2',
    mainCategory: 'footwear',
    subCategory: null,
    link: '',
  },
  {
    id: '00034',
    imageUrl: '/temp/avatar/nft_footwear_3.png',
    rarity: 'common',
    name: 'footwear_3',
    mainCategory: 'footwear',
    subCategory: null,
    link: '',
  },
  {
    id: '00035',
    imageUrl: '/temp/avatar/nft_footwear_4.png',
    rarity: 'common',
    name: 'footwear_4',
    mainCategory: 'footwear',
    subCategory: null,
    link: '',
  },
  {
    id: '00036',
    imageUrl: '/temp/avatar/nft_footwear_5.png',
    rarity: 'common',
    name: 'footwear_5',
    mainCategory: 'footwear',
    subCategory: null,
    link: '',
  },
  {
    id: '00037',
    imageUrl: '/temp/avatar/avatar_bg.png',
    rarity: 'common',
    name: 'avatar_bg',
    mainCategory: 'background',
    subCategory: null,
    link: '',
  },
]
