export type MainCategory =
  | 'fullSet'
  | 'upperClothing'
  | 'lowerClothing'
  | 'footwear'
  | 'face'
  | 'skin'
  | 'hair'
  | 'accessories'
  | 'background'
export type SubCategory = 'hair-accessories' | 'eye-accessories' | 'ear-accessories' | 'body-accessories'
